import type { Metadata } from "next";
import { Orbitron, Rajdhani, Inter, JetBrains_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import "@rainbow-me/rainbowkit/styles.css";

import "./globals.css";
import ErrorBoundary from "@/components/ErrorBoundary";
import { ThemeProvider } from "@/contexts/ThemeContext";
import WalletProvider from "@/components/WalletProvider";

const orbitron = Orbitron({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-orbitron", // 定义 CSS 变量名
  weight: ["700", "900"], // 只加载您需要的字重
});

const rajdhani = Rajdhani({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rajdhani",
  weight: ["600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "600"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains-mono",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${rajdhani.variable} ${inter.variable} ${jetbrainsMono.variable}`}
      >
        <ErrorBoundary>
          <ThemeProvider defaultTheme="dark">
            <WalletProvider>
              <TooltipProvider>
                <Toaster />
                {/* Scanline effect for cyberpunk aesthetic */}
                <div className="scanline" />
                {children}
              </TooltipProvider>
            </WalletProvider>
          </ThemeProvider>

        </ErrorBoundary>
      </body>
    </html>
  );
}
